---
namemap: 
  theta:
    - V2  
    - CL
    - V3
    - Q
    - KA
    - ERRPROP
  sigma:
    - DUMMY
  omega:
    - nV2
    - nCL    
    - nV3
    - nQ
    - nKA
    - nOCC1_on_V

parameters:
  - name: V2
    label: Central volume V2
    units: L
    trans: 
    type: Structural

  - name: CL
    label: Clearance CL
    units: L/h
    trans: 
    type: Structural
    
  - name: V3
    label: Peripheral volume V3
    units: L
    trans: 
    type: Structural    
  
  - name: Q
    label: Peripheral clearance Q
    units: L/h
    trans: 
    type: Structural

  - name: KA
    label: Absorption rate constant Ka
    units: "h<sup>-1</sup>"
    trans: 
    type: Structural
    
  - name: nV2
    label: On V2
    type: IIV
    relatedTo: V2       
       
  - name: nCL,nV2
    label: Correlation CL, V2
    type: IIV
    relatedTo: CL,V2     
    
  - name: nCL
    label: On CL
    type: IIV
    relatedTo: CL     
        
  - name: nV3
    label: On V3
    type: IIV
    relatedTo: V3

  - name: nQ
    label: On Q
    type: IIV
    relatedTo: Q

  - name: nKA
    label: On Ka
    type: IIV
    relatedTo: KA

  - name: ERRPROP
    label: Proportional
    units: 
    trans: 
    type: RUV

